2025-02-28 20:03:56,633 [INFO] Клиент запустился
2025-02-28 20:03:58,672 [ERROR] Ошибка подключения к серверу: HTTPConnectionPool(host='127.0.0.1', port=4000): Max retries exceeded with url: /api/time (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000271D61A3830>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))
